In [1]:
import numpy as np

### Data type and memory

In [9]:
a = np.array([1,2,3], dtype='int32')
b = np.array([1,2,3], dtype='float')

In [10]:
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [12]:
a.nbytes

12

In [13]:
b.nbytes

24

In [16]:
a.itemsize

4

In [17]:
b.itemsize

8

### Indexing

In [33]:
a = np.arange(1,28).reshape(3,3,3)
b = np.arange(1,17).reshape(2,8)

In [34]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [35]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [36]:
# get specific element 3D: a[matrix,row,column] or a[matrix][row][column]
print(a[0,2,1])
print(a[0][2][1])

8
8


In [37]:
# get specific element 2D: b[row,column] or b[row][column]
print(b[1,6])
print(b[1][6])

15
15


In [38]:
# get entire row 2D : b[1,:] or b[1]
print(b[1,:])
print(b[1])

[ 9 10 11 12 13 14 15 16]
[ 9 10 11 12 13 14 15 16]


In [39]:
# get entire column 2D : b[:,2]
print(b[:,2])

[ 3 11]


In [45]:
# get diagonal elements all 2d arrays
np.diagonal(a, axis1 = 1, axis2 = 2)

array([[ 1,  5,  9],
       [10, 14, 18],
       [19, 23, 27]])

In [46]:
# get middle elements of all 2d
a[:,1,1]

array([ 5, 14, 23])

### Initializing arrays

In [47]:
# all zeros
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# all 1s
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# any other value
np.full(shape=(2,3), fill_value=9)

array([[9, 9, 9],
       [9, 9, 9]])

In [53]:
# using shape of existing array
np.full_like(a=b, fill_value=99)

array([[99, 99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99, 99]])

In [54]:
# random decimal numbers
np.random.rand(2,3)

array([[0.01477741, 0.19073741, 0.66158442],
       [0.18652025, 0.95835699, 0.74318892]])

In [57]:
np.random.random_sample(size=(2,3))

array([[0.66230159, 0.60172247, 0.28035228],
       [0.05537939, 0.9523167 , 0.45221402]])

In [59]:
# random integer numbers
np.random.randint(low=5, high=10, size=(2,3))

array([[6, 6, 5],
       [6, 6, 7]])

In [60]:
# identity matrix
np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
# repeat existing array
arr = np.array([[1,6,9]])
print(arr)
np.repeat(a=arr, repeats=3, axis=0)

[[1 6 9]]


array([[1, 6, 9],
       [1, 6, 9],
       [1, 6, 9]])

In [76]:
# some fancy stuff

output = np.ones(shape=(5,5))
print(output)

zeros = np.zeros(shape=(3,3))
zeros[1,1] = 9

output[1:-1, 1:-1] = zeros

print()
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copy !!!

In [77]:
a = np.array([1,2,3])
b = a #wrong
b = a.copy() #right

### Arithmetic Operations

In [78]:
a = np.array([2,4,6,8])
print(a+1)
print(a-1)
print(a*2)
print(a/2)

[3 5 7 9]
[1 3 5 7]
[ 4  8 12 16]
[1. 2. 3. 4.]


In [80]:
print(np.sin(a))
print(np.cos(a))

[ 0.90929743 -0.7568025  -0.2794155   0.98935825]
[-0.41614684 -0.65364362  0.96017029 -0.14550003]


In [83]:
# sum
print(a.sum())

#mean
print(a.mean())

20
5.0


### Linear algebra & Stats

In [84]:
# matrix multiplication

a = np.ones(shape=(2,3))
print(a)

b = np.full(shape=(3,2), fill_value=3)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [86]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
print(np.min(a, axis=None))
print(np.min(a, axis=1)) # i.e consider all columns for a single row at a time
print(np.min(a, axis=0)) # i.e. consider all rows for a single column at a time

1
[1 4]
[1 2 3]


### Reshape

In [92]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# .reshape takes a tuple as an argument. Hence .reshape( (rows,columns) )
print(a.reshape((3,3)))
print(a.reshape((3,-1))) # passing -1 asks numpy to figure out the dimension based on number of elements

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Stacking

In [109]:
a = np.arange(6).reshape(2,-1)
b = np.arange(6,12).reshape(2,-1)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [110]:
np.vstack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [111]:
np.hstack((a,b))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### Load from file

In [ ]:
# np.genfromtxt(filename, delimiter=',')

### Masking

In [116]:
a = np.random.randint(1,100, size=(4,10))
a

array([[68, 36,  8, 71, 46, 59, 31, 57, 51, 82],
       [41, 90, 61, 96, 23, 48,  6, 92, 33, 76],
       [38, 25, 51, 20, 64, 81, 84, 49,  6, 69],
       [25,  1, 74, 13, 61, 51, 22, 73, 48, 95]])

In [133]:
# even numbers mask
mask = a%2==0
print(mask)
print(a[mask])

[[ True  True  True False  True False False False False  True]
 [False  True False  True False  True  True  True False  True]
 [ True False False  True  True False  True False  True False]
 [False False  True False False False  True False  True False]]
[68 36  8 46 82 90 96 48  6 92 76 38 20 64 84  6 74 22 48]


In [124]:
# np.any()
print(np.any(a<5, axis=0))
print(np.any(a<5, axis=1))

[False  True False False False False False False False False]
[False False False  True]


In [127]:
# np.all()
print(np.all(a>6, axis=0))
print(np.all(a>6, axis=1))

[ True False  True  True  True  True False  True False  True]
[ True False False False]


### Multiple masks

In [128]:
a

array([[68, 36,  8, 71, 46, 59, 31, 57, 51, 82],
       [41, 90, 61, 96, 23, 48,  6, 92, 33, 76],
       [38, 25, 51, 20, 64, 81, 84, 49,  6, 69],
       [25,  1, 74, 13, 61, 51, 22, 73, 48, 95]])

In [136]:
mask = ((a>20) & (a<50))
print(mask)

[[False  True False False  True False  True False False False]
 [ True False False False  True  True False False  True False]
 [ True  True False False False False False  True False False]
 [ True False False False False False  True False  True False]]


In [137]:
negative_mask = ~mask
print(negative_mask)

[[ True False  True  True False  True False  True  True  True]
 [False  True  True  True False False  True  True False  True]
 [False False  True  True  True  True  True False  True  True]
 [False  True  True  True  True  True False  True False  True]]


In [138]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [139]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [140]:
# get 2,8,14,20
a[ [0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [151]:
# get 4,5 24,25 29,30
# i.e. specific rows and continuos specific columns
a[ [0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])